name: CI smoke test

"on":
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - name: Echo
        run: echo "actions runner is alive"
      - name: Resolve FTP action
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: example.com
          username: x
          password: x
          dry-run: true
          local-dir: ./public/
